services:
  app_registration:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:mysql://datasource:3306/login-db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      DATASOURCE_USERNAME: test
      DATASOURCE_PASSWORD: test
